---
abstract: 'Count packages, subs, lines, etc. of many files.'
author:
  - matisse@eigenstate.net
build_requires:
  Data::Dumper: '0'
  File::Spec: '0'
  Module::Build: '0.2612'
  Readonly: '1.03'
  Test::Compile: v1.1.0
  Test::Pod: '1'
  Test::Pod::Coverage: '1.04'
configure_requires:
  Module::Build: '0.4'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-Metrics-Simple
provides:
  Perl::Metrics::Simple:
    file: lib/Perl/Metrics/Simple.pm
    version: v1.0.3
  Perl::Metrics::Simple::Analysis:
    file: lib/Perl/Metrics/Simple/Analysis.pm
    version: v1.0.3
  Perl::Metrics::Simple::Analysis::File:
    file: lib/Perl/Metrics/Simple/Analysis/File.pm
    version: v1.0.3
  Perl::Metrics::Simple::Output:
    file: lib/Perl/Metrics/Simple/Output.pm
    version: v1.0.3
  Perl::Metrics::Simple::Output::HTML:
    file: lib/Perl/Metrics/Simple/Output/HTML.pm
    version: v1.0.3
  Perl::Metrics::Simple::Output::JSON:
    file: lib/Perl/Metrics/Simple/Output/JSON.pm
    version: v1.0.3
  Perl::Metrics::Simple::Output::PlainText:
    file: lib/Perl/Metrics/Simple/Output/PlainText.pm
    version: v1.0.3
recommends:
  Readonly::XS: '1.02'
requires:
  Carp: '0'
  Data::Dumper: '0'
  File::Basename: '0'
  File::Find: '1.01'
  Getopt::Long: '0'
  IO::File: '1.14'
  PPI: '1.113'
  Pod::Usage: '0'
  Readonly: '1.03'
  Statistics::Basic::Mean: '0'
  Statistics::Basic::Median: '0'
  Statistics::Basic::StdDev: '0'
resources:
  bugtracker: https://github.com/matisse/Perl-Metrics-Simple/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/matisse/Perl-Metrics-Simple
version: v1.0.3
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
